// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/captechconsulting/go-microservice-templates/sqs-lambda/internal/models"
)

// MockUserCreator is an autogenerated mock type for the userCreator type
type MockUserCreator struct {
	mock.Mock
}

type MockUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCreator) EXPECT() *MockUserCreator_Expecter {
	return &MockUserCreator_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockUserCreator) CreateUser(ctx context.Context, user models.User) (int, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (int, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) int); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserCreator_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserCreator_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *MockUserCreator_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUserCreator_CreateUser_Call {
	return &MockUserCreator_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserCreator_CreateUser_Call) Run(run func(ctx context.Context, user models.User)) *MockUserCreator_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *MockUserCreator_CreateUser_Call) Return(_a0 int, _a1 error) *MockUserCreator_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserCreator_CreateUser_Call) RunAndReturn(run func(context.Context, models.User) (int, error)) *MockUserCreator_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserCreator creates a new instance of MockUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCreator {
	mock := &MockUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
