### list users
GET http://localhost:8080/api/user

### Update a user by ID
PUT http://localhost:8080/api/user/1
Content-Type: application/json

{
  "id": 1,
  "first_name": "Johnny",
  "last_name": "Doe",
  "role": "Customer",
  "user_id": 1001
}