template: testify
filename: "{{.InterfaceName | snakecase }}.go"
dir: "{{.InterfaceDir}}/mocks"
pkgname: mocks
structname: "Mock{{.InterfaceName | camelcase | firstUpper }}"
packages:
  github.com/captechconsulting/go-microservice-templates/api/internal/handlers:
    interfaces:
      userLister:
      userUpdater: