template: matryer
dir: "{{.InterfaceDir}}"
filename: "mocks.go"
pkgname: "handlers"
structname: "moq{{.InterfaceName | camelcase | firstUpper }}"
packages:
  github.com/captechconsulting/go-microservice-templates/api/internal/handlers:
    interfaces:
      userLister:
      userUpdater: