// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package handlers

import (
	"context"
	"sync"

	"github.com/captechconsulting/go-microservice-templates/api/internal/models"
)

// Ensure that moqUserLister does implement userLister.
// If this is not the case, regenerate this file with mockery.
var _ userLister = &moqUserLister{}

// moqUserLister is a mock implementation of userLister.
//
//	func TestSomethingThatUsesuserLister(t *testing.T) {
//
//		// make and configure a mocked userLister
//		mockeduserLister := &moqUserLister{
//			ListUsersFunc: func(ctx context.Context) ([]models.User, error) {
//				panic("mock out the ListUsers method")
//			},
//		}
//
//		// use mockeduserLister in code that requires userLister
//		// and then make assertions.
//
//	}
type moqUserLister struct {
	// ListUsersFunc mocks the ListUsers method.
	ListUsersFunc func(ctx context.Context) ([]models.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListUsers holds details about calls to the ListUsers method.
		ListUsers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockListUsers sync.RWMutex
}

// ListUsers calls ListUsersFunc.
func (mock *moqUserLister) ListUsers(ctx context.Context) ([]models.User, error) {
	if mock.ListUsersFunc == nil {
		panic("moqUserLister.ListUsersFunc: method is nil but userLister.ListUsers was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListUsers.Lock()
	mock.calls.ListUsers = append(mock.calls.ListUsers, callInfo)
	mock.lockListUsers.Unlock()
	return mock.ListUsersFunc(ctx)
}

// ListUsersCalls gets all the calls that were made to ListUsers.
// Check the length with:
//
//	len(mockeduserLister.ListUsersCalls())
func (mock *moqUserLister) ListUsersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListUsers.RLock()
	calls = mock.calls.ListUsers
	mock.lockListUsers.RUnlock()
	return calls
}

// Ensure that moqUserUpdater does implement userUpdater.
// If this is not the case, regenerate this file with mockery.
var _ userUpdater = &moqUserUpdater{}

// moqUserUpdater is a mock implementation of userUpdater.
//
//	func TestSomethingThatUsesuserUpdater(t *testing.T) {
//
//		// make and configure a mocked userUpdater
//		mockeduserUpdater := &moqUserUpdater{
//			UpdateUserFunc: func(ctx context.Context, ID int, user models.User) (models.User, error) {
//				panic("mock out the UpdateUser method")
//			},
//		}
//
//		// use mockeduserUpdater in code that requires userUpdater
//		// and then make assertions.
//
//	}
type moqUserUpdater struct {
	// UpdateUserFunc mocks the UpdateUser method.
	UpdateUserFunc func(ctx context.Context, ID int, user models.User) (models.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// UpdateUser holds details about calls to the UpdateUser method.
		UpdateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the ID argument value.
			ID int
			// User is the user argument value.
			User models.User
		}
	}
	lockUpdateUser sync.RWMutex
}

// UpdateUser calls UpdateUserFunc.
func (mock *moqUserUpdater) UpdateUser(ctx context.Context, ID int, user models.User) (models.User, error) {
	if mock.UpdateUserFunc == nil {
		panic("moqUserUpdater.UpdateUserFunc: method is nil but userUpdater.UpdateUser was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		ID   int
		User models.User
	}{
		Ctx:  ctx,
		ID:   ID,
		User: user,
	}
	mock.lockUpdateUser.Lock()
	mock.calls.UpdateUser = append(mock.calls.UpdateUser, callInfo)
	mock.lockUpdateUser.Unlock()
	return mock.UpdateUserFunc(ctx, ID, user)
}

// UpdateUserCalls gets all the calls that were made to UpdateUser.
// Check the length with:
//
//	len(mockeduserUpdater.UpdateUserCalls())
func (mock *moqUserUpdater) UpdateUserCalls() []struct {
	Ctx  context.Context
	ID   int
	User models.User
} {
	var calls []struct {
		Ctx  context.Context
		ID   int
		User models.User
	}
	mock.lockUpdateUser.RLock()
	calls = mock.calls.UpdateUser
	mock.lockUpdateUser.RUnlock()
	return calls
}
