AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample GoLand Lambda

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  ListUsers:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENV: !Ref ENV
          LOG_LEVEL: !Ref LOG_LEVEL
          DATABASE_CONTAINER_NAME: !Ref DATABASE_CONTAINER_NAME
          DATABASE_NAME: !Ref DATABASE_NAME
          DATABASE_USER: !Ref DATABASE_USER
          DATABASE_PASSWORD: !Ref DATABASE_PASSWORD
          DATABASE_HOST: !Ref DATABASE_HOST
          DATABASE_PORT: !Ref DATABASE_PORT
          DATABASE_RETRY_DURATION_SECONDS: !Ref DATABASE_RETRY_DURATION_SECONDS
      CodeUri: cmd/list/
      Events:
        ListUser:
          Type: Api
          Properties:
            Path: /api/user
            Method: GET
  UpdateUser:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENV: !Ref ENV
          LOG_LEVEL: !Ref LOG_LEVEL
          DATABASE_CONTAINER_NAME: !Ref DATABASE_CONTAINER_NAME
          DATABASE_NAME: !Ref DATABASE_NAME
          DATABASE_USER: !Ref DATABASE_USER
          DATABASE_PASSWORD: !Ref DATABASE_PASSWORD
          DATABASE_HOST: !Ref DATABASE_HOST
          DATABASE_PORT: !Ref DATABASE_PORT
          DATABASE_RETRY_DURATION_SECONDS: !Ref DATABASE_RETRY_DURATION_SECONDS
      CodeUri: cmd/update/
      Events:
        UpdateUser:
          Type: Api
          Properties:
            Path: /api/user/{ID}
            Method: PUT
