with-expecter: true
packages:
  github.com/captechconsulting/go-microservice-templates/sqs-lambda/internal/handlers:
    config:
      filename: "{{.InterfaceName | snakecase }}.go"
      dir: "{{.InterfaceDir}}/mock"
      mockname: "Mock{{.InterfaceName | camelcase | firstUpper }}"
      outpkg: "mock"
      inpackage: false
    interfaces:
      userCreator: